////////////////////////////////////////////////////////////////////
// Copyright (C) Alexander Telyatnikov, Ivan Keliukh, Yegor Anchishkin, SKIF Software, 1999-2013. Kiev, Ukraine
// All rights reserved
// This file was released under the GPLv2 on June 2015.
////////////////////////////////////////////////////////////////////
/*************************************************************************
*
* File: Write.cpp
*
* Module: UDF File System Driver (Kernel mode execution only)
*
* Description:
*   Contains code to handle the "Write" dispatch entry point.
*
*************************************************************************/

#include            "udffs.h"

// define the file specific bug-check id
#define         UDF_BUG_CHECK_ID                UDF_FILE_WRITE

/*************************************************************************
*
* Function: UDFCommonWrite()
*
* Description:
*   The actual work is performed here. This routine may be invoked in one'
*   of the two possible contexts:
*   (a) in the context of a system worker thread
*   (b) in the context of the original caller
*
* Expected Interrupt Level (for execution) :
*
*  IRQL_PASSIVE_LEVEL
*
* Return Value: STATUS_SUCCESS/Error
*
*************************************************************************/
NTSTATUS
UDFCommonWrite(
    PIRP_CONTEXT IrpContext,
    PIRP Irp)
{
    NTSTATUS Status = STATUS_SUCCESS;
    PIO_STACK_LOCATION IrpSp = IoGetCurrentIrpStackLocation(Irp);
    LONGLONG StartingOffset;
    ULONG ByteCount;
    LONGLONG ByteRange;
    ULONG TruncatedLength;
    SIZE_T                  NumberBytesWritten = 0;
    PFILE_OBJECT            FileObject = NULL;
    TYPE_OF_OPEN TypeOfOpen;
    PFCB                    Fcb = NULL;
    PCCB                    Ccb = NULL;
    PVCB                    Vcb = NULL;
    PVOID                   SystemBuffer = NULL;

    LONGLONG                ASize;
    LONGLONG                OldVDL;

    BOOLEAN                 PagingIoResourceAcquired = FALSE;
    BOOLEAN                 MainResourceAcquired = FALSE;
    BOOLEAN                 VcbAcquired = FALSE;

    BOOLEAN                 Wait = FALSE;
    BOOLEAN                 PagingIo = FALSE;
    BOOLEAN                 NonCachedIo = FALSE;
    BOOLEAN                 SynchronousIo = FALSE;
    BOOLEAN                 IsLazyWriteThread = FALSE;
    BOOLEAN                 WriteToEOF = FALSE;
    BOOLEAN                 FileSizesChanged = FALSE;
    BOOLEAN                 RecursiveWriteThrough = FALSE;
    BOOLEAN                 ZeroBlock = FALSE;
    BOOLEAN                 ZeroBlockDone = FALSE;
    UDF_IO_CONTEXT          LocalIoContext;

    // Examine our input parameters to determine if this is noncached and/or
    // a paging io operation.

    Wait = BooleanFlagOn(IrpContext->Flags, IRP_CONTEXT_FLAG_WAIT);
    PagingIo = FlagOn(Irp->Flags, IRP_PAGING_IO);
    NonCachedIo = FlagOn(Irp->Flags, IRP_NOCACHE);
    SynchronousIo = FlagOn(IrpSp->FileObject->Flags, FO_SYNCHRONOUS_IO);

    FileObject = IrpSp->FileObject;

    // Extract and decode the file object.

    TypeOfOpen = UDFDecodeFileObject(IrpSp->FileObject, &Fcb, &Ccb);

    if (TypeOfOpen != UserFileOpen &&
        TypeOfOpen != UserVolumeOpen &&
       (TypeOfOpen != StreamFileOpen || !NonCachedIo || !PagingIo)) {

        UDFCompleteRequest(IrpContext, Irp, STATUS_INVALID_DEVICE_REQUEST);
        return STATUS_INVALID_DEVICE_REQUEST;
    }

    Vcb = Fcb->Vcb;

    // Handle bitmap internal stream PagingIo (generated by Cache Manager flush)
    // Must be before ASSERT_CCB — bitmap stream has no Ccb.

    if (TypeOfOpen == StreamFileOpen && PagingIo && Fcb == Vcb->BitmapFcb) {

        if (!Wait) {
            Wait = TRUE;
            SetFlag(IrpContext->Flags, IRP_CONTEXT_FLAG_WAIT);
        }

        StartingOffset = IrpSp->Parameters.Write.ByteOffset.QuadPart;
        ByteCount = IrpSp->Parameters.Write.Length;
        ULONG NumberBytesWritten = 0;

        Status = UDFLockUserBuffer(IrpContext, ByteCount, IoReadAccess);
        if (NT_SUCCESS(Status)) {
            PVOID SystemBuffer = UDFMapUserBuffer(Irp);
            if (SystemBuffer) {

                LONGLONG Vbn = StartingOffset >> Vcb->SectorShift;
                LONGLONG Psn;
                LONGLONG SectorCount;

                if (FsRtlLookupLargeMcbEntry(&Vcb->BitmapMcb, Vbn, &Psn,
                        &SectorCount, NULL, NULL, NULL)) {

                    ULONG SectorsToWrite = (ULONG)min(SectorCount,
                        (LONGLONG)((ByteCount + Vcb->SectorSize - 1) >> Vcb->SectorShift));
                    SIZE_T WrittenBytes;

                    Status = UDFWriteSectors(IrpContext, Vcb, TRUE, (ULONG)Psn,
                        SectorsToWrite, FALSE, (PCHAR)SystemBuffer, &WrittenBytes);
                    NumberBytesWritten = (ULONG)WrittenBytes;
                    if (!NT_SUCCESS(Status)) {
                        UDFPrint(("UDF BM: PagingIo WRITE FAILED Vbn=%I64x Psn=%I64x Sectors=%x Status=%x\n",
                            Vbn, Psn, SectorsToWrite, Status));
                    }
                } else {
                    UDFPrint(("UDF BM: PagingIo WRITE MCB MISS Vbn=%I64x ByteCount=%x\n", Vbn, ByteCount));
                    Status = STATUS_NONEXISTENT_SECTOR;
                }
                UDFUnlockCallersBuffer(IrpContext, Irp, SystemBuffer);
            } else {
                Status = STATUS_INVALID_USER_BUFFER;
            }
        }

        Irp->IoStatus.Information = NumberBytesWritten;
        UDFCompleteRequest(IrpContext, Irp, Status);
        return Status;
    }

    ASSERT_CCB(Ccb);
    ASSERT_FCB(Fcb);
    ASSERT_VCB(Vcb);

    // Check if this volume has already been shut down.  If it has, fail
    // this write request.

    if (FlagOn(Vcb->VcbState, VCB_STATE_SHUTDOWN)) {

        UDFCompleteRequest(IrpContext, Irp, STATUS_TOO_LATE);
        return STATUS_TOO_LATE;
    }

    if (FlagOn(Vcb->VcbState, VCB_STATE_VOLUME_READ_ONLY) && (TypeOfOpen != UserVolumeOpen)) {

        if (FlagOn(Vcb->VcbState, VCB_STATE_MEDIA_WRITE_PROTECT)) {
            Status = STATUS_MEDIA_WRITE_PROTECTED;
        }
        else if (PagingIo) {
            Status = STATUS_FILE_INVALID;
        }
        else {
            Status = FlagOn(Vcb->VcbState, VCB_STATE_MOUNTED_DIRTY) ?
                     STATUS_VOLUME_DIRTY : STATUS_ACCESS_DENIED;
        }

        UDFCompleteRequest(IrpContext, Irp, Status);
        return Status;
    }

    // If this is async paging io then check if we are being called by the mapped page writer.
    // Convert it back to synchronous if not.

    if (!Wait && PagingIo) {

        Wait = TRUE;
        SetFlag(IrpContext->Flags, IRP_CONTEXT_FLAG_WAIT);
    }

    StartingOffset = IrpSp->Parameters.Write.ByteOffset.QuadPart;
    ByteCount = IrpSp->Parameters.Write.Length;
    ByteRange = StartingOffset + ByteCount;

    Irp->IoStatus.Information = 0;

    // Check if writing to end of file (FILE_WRITE_TO_END_OF_FILE = -1)

    BOOLEAN WriteToEof = (StartingOffset < 0);

    // Validate file offset - overflow check only for normal offsets

    if (((MAXLONGLONG - StartingOffset) < ByteCount) && !WriteToEof) {

        UDFCompleteRequest(IrpContext, Irp, STATUS_INVALID_PARAMETER);
        return STATUS_INVALID_PARAMETER;
    }

    // Handle zero-length write
    if (ByteCount == 0) {

        UDFCompleteRequest(IrpContext, Irp, STATUS_SUCCESS);
        return STATUS_SUCCESS;
    }

    // See if we have to defer the write.

    if (!NonCachedIo &&
        !CcCanIWrite(FileObject,
                     ByteCount,
                     (BOOLEAN)(Wait && !BooleanFlagOn(IrpContext->Flags, IRP_CONTEXT_FLAG_IN_FSP)),
                     BooleanFlagOn(IrpContext->Flags, IRP_CONTEXT_FLAG_DEFERRED_WRITE))) {

        BOOLEAN Retrying = BooleanFlagOn(IrpContext->Flags, IRP_CONTEXT_FLAG_DEFERRED_WRITE);

        UDFPrePostIrp(IrpContext, Irp);

        SetFlag(IrpContext->Flags, IRP_CONTEXT_FLAG_DEFERRED_WRITE);

        CcDeferWrite(FileObject, UDFDeferredWriteCallBack, IrpContext, Irp, ByteCount, Retrying);
        return STATUS_PENDING;
    }

    _SEH2_TRY {

        // If this is a request at IRQL DISPATCH_LEVEL, then post the request
        if (IrpSp->MinorFunction & IRP_MN_DPC) {
            try_return(Status = STATUS_PENDING);
        }

        // If this is a non paging write to a data stream object we have to
        // check for access according to the current state op/filelocks.
        //
        // Note that after this point, operations will be performed on the file.
        // No modifying activity can occur prior to this point in the write
        // path.

        if (!PagingIo && TypeOfOpen == UserFileOpen) {

            // And finally check the regular file locks.

            if (Fcb->FileLock != NULL &&
                !FsRtlCheckLockForWriteAccess(Fcb->FileLock, Irp )) {

                try_return(Status = STATUS_FILE_LOCK_CONFLICT);
            }
        }

        // **********
        // Is this a write of the volume itself ?
        // **********
        if (Fcb == Fcb->Vcb->VolumeDasdFcb) {
            // Yup, we need to send this on to the disk driver after
            //  validation of the offset and length.

            if (!Wait)
                try_return(Status = STATUS_PENDING);
            // I dislike the idea of writing to not locked media
            if (!(Vcb->VcbState & VCB_STATE_LOCKED)) {
                try_return(Status = STATUS_ACCESS_DENIED);
            }

            // Acquire the volume resource exclusive
            UDFAcquireVcbExclusive(IrpContext, Vcb, FALSE);
            VcbAcquired = TRUE;

            // I dislike the idea of writing to mounted media too, but M$ has another point of view...
            if (Vcb->VcbCondition == VcbMounted) {
                // flush system cache
                UDFFlushVolume(IrpContext, Vcb);
            }

            // Forward the request to the lower level driver
            // Lock the callers buffer
            if (!NT_SUCCESS(Status = UDFLockUserBuffer(IrpContext, ByteCount, IoReadAccess))) {
                try_return(Status);
            }
            SystemBuffer = UDFMapUserBuffer(Irp);
            if (!SystemBuffer)
                try_return(Status = STATUS_INVALID_USER_BUFFER);

            // Make sure, that volume will never be quick-remounted
            // It is very important for ChkUdf utility.
            Vcb->SerialNumber--;
            // Perform actual Write
            Status = UDFReadWriteSectors(IrpContext, Vcb,
                           StartingOffset, ByteCount,
                           TRUE, SystemBuffer, TRUE);
            NumberBytesWritten = NT_SUCCESS(Status) ? ByteCount : 0;
            UDFUnlockCallersBuffer(IrpContext, Irp, SystemBuffer);
            try_return(Status);
        }

        // Validate start offset and length supplied.
        // Here is a special check that determines whether the caller wishes to
        // begin the write at current end-of-file (whatever the value of that
        // offset might be)
        if (StartingOffset == -1) {
            WriteToEOF = TRUE;
            StartingOffset = Fcb->Header.FileSize.QuadPart;
        }

        // Paging I/O write operations are special. If paging i/o write
        // requests begin beyond end-of-file, the request should be no-oped
        // If paging i/o
        // requests extend beyond current end of file, they should be truncated
        // to current end-of-file.
        if (PagingIo && (WriteToEOF || ((StartingOffset + ByteCount) > Fcb->Header.FileSize.QuadPart))) {
            if (StartingOffset > Fcb->Header.FileSize.QuadPart) {
                TruncatedLength = 0;
            } else {
                TruncatedLength = (ULONG)(Fcb->Header.FileSize.QuadPart - StartingOffset);
            }
            if (!TruncatedLength) try_return(Status = STATUS_SUCCESS);
        } else {
            TruncatedLength = ByteCount;
        }

        // There are certain complications that arise when the same file stream
        // has been opened for cached and non-cached access. The FSD is then
        // responsible for maintaining a consistent view of the data seen by
        // the caller.
        // If this happens to be a non-buffered I/O, we should __try to flush the
        // cached data (if some other file object has already initiated caching
        // on the file stream). We should also __try to purge the cached
        // information though the purge will probably fail if the file has been
        // mapped into some process' virtual address space
        // WARNING !!! we should not flush data beyond valid data length
        if (!PagingIo &&
            NonCachedIo &&
            Fcb->FcbNonpaged->SegmentObject.DataSectionObject &&
            TruncatedLength &&
            (StartingOffset < Fcb->Header.FileSize.QuadPart)) {

            UDFAcquireFcbExclusive(IrpContext, Fcb, FALSE);

            MainResourceAcquired = TRUE;

            // Flush and then attempt to purge the cache
            if ((StartingOffset + TruncatedLength) > Fcb->Header.FileSize.QuadPart) {
                NumberBytesWritten = TruncatedLength;
            } else {
                NumberBytesWritten = (ULONG)(Fcb->Header.FileSize.QuadPart - StartingOffset);
            }

            CcFlushCache(&Fcb->FcbNonpaged->SegmentObject,
                         WriteToEof ? &Fcb->Header.FileSize : (PLARGE_INTEGER)&StartingOffset,
                         NumberBytesWritten,
                         &Irp->IoStatus);

            // If the flush failed, return error to the caller
            if (!NT_SUCCESS(Status = Irp->IoStatus.Status)) {
                NumberBytesWritten = 0;
                try_return(Status);
            }

            // Attempt the purge
            BOOLEAN SuccessfulPurge = CcPurgeCacheSection(&Fcb->FcbNonpaged->SegmentObject,
                                                          (PLARGE_INTEGER)&StartingOffset,
                                                          NumberBytesWritten,
                                                          FALSE);
            NumberBytesWritten = 0;

            // We are finished with our flushing and purging
            if (!SuccessfulPurge) {
                try_return(Status = STATUS_PURGE_FAILED);            
            }
        }

        // Determine if we were called by the lazywriter.

        IsLazyWriteThread = (Fcb->LazyWriteThread == PsGetCurrentThread());

        // Acquire the appropriate FCB resource
        if (PagingIo) {

            // For PagingIo: FcbResource already acquired by UDFAcqLazyWrite/UDFFastIoAcqModWrite
            // callback before this function is called

            if (Fcb->FcbState & UDF_FCB_EMBEDDED_DATA) {
                ASSERT_EXCLUSIVE_FCB(Fcb);
            }
            else {
                ASSERT_SHARED_FCB(Fcb);
            }

            ASSERT(NonCachedIo);

        } else {
            // Try to acquire the FCB MainResource shared
            if (NonCachedIo) {
                if (!MainResourceAcquired) {
                    if (!UDFAcquireSharedWaitForExclusive(&Fcb->FcbNonpaged->FcbResource, Wait)) {
                        try_return(Status = STATUS_PENDING);
                    }
                    MainResourceAcquired = TRUE;
                }
            } else {
                if (!MainResourceAcquired) {
                    UDF_CHECK_PAGING_IO_RESOURCE(Fcb);
                    if (!UDFAcquireResourceShared(&Fcb->FcbNonpaged->FcbResource, Wait)) {
                        try_return(Status = STATUS_PENDING);
                    }
                    MainResourceAcquired = TRUE;
                }
            }
        }

        if (!Ccb || !FlagOn(Ccb->Flags, CCB_FLAG_DISMOUNT_ON_CLOSE)) {

            UDFVerifyFcbOperation(IrpContext, Fcb, Ccb);
        }

        //  Here is the deal with ValidDataLength and FileSize:
        //
        //  Rule 1: PagingIo is never allowed to extend file size.
        //
        //  Rule 2: Only the top level requestor may extend Valid
        //          Data Length.  This may be paging IO, as when a
        //          a user maps a file, but will never be as a result
        //          of cache lazy writer writes since they are not the
        //          top level request.
        //
        //  Rule 3: If, using Rules 1 and 2, we decide we must extend
        //          file size or valid data, we take the Fcb exclusive.

        // Check whether the current request will extend the file size,
        // or the valid data length (if the FSD supports the concept of a
        // valid data length associated with the file stream). In either case,
        // inform the Cache Manager at this time using CcSetFileSizes() about
        // the new file length. Note that real FSD implementations will have to
        // first allocate enough on-disk space at this point (before they
        // inform the Cache Manager about the new size) to ensure that the write
        // will subsequently not fail due to lack of disk space.

        OldVDL = Fcb->Header.ValidDataLength.QuadPart;
        ZeroBlock = (StartingOffset > OldVDL);

        if (!PagingIo &&
            !RecursiveWriteThrough &&
            !IsLazyWriteThread) {

            BOOLEAN ExtendFS = FALSE;

            ExtendFS = (StartingOffset + TruncatedLength > Fcb->Header.FileSize.QuadPart);

            if ( WriteToEOF || ZeroBlock || ExtendFS) {
                // we are extending the file;

                if (!Wait)
                    try_return(Status = STATUS_PENDING);
//                CanWait = TRUE;

                UDFAcquirePagingIoExclusive(IrpContext, Fcb);
                PagingIoResourceAcquired = TRUE;

                if (ExtendFS) {
                    Status = UDFResizeFile__(IrpContext, Vcb, Fcb->FileInfo, StartingOffset + TruncatedLength);

                    if (!NT_SUCCESS(Status)) {
                        try_return(Status);
                    }
                    FileSizesChanged = TRUE;
                    // ... and inform the Cache Manager about it

                    Fcb->Header.FileSize.QuadPart = StartingOffset + TruncatedLength;

                    if (Fcb->Header.AllocationSize.QuadPart < (LONGLONG)LlSectorAlign(Vcb, Fcb->Header.FileSize.QuadPart)) {

                        Fcb->Header.AllocationSize.QuadPart = LlSectorAlign(Vcb, Fcb->Header.FileSize.QuadPart);
                    }
                }

                UDFReleasePagingIo(IrpContext, Fcb);
                PagingIoResourceAcquired = FALSE;

                if (CcIsFileCached(FileObject)) {
                    if (ExtendFS) {
                        MmPrint(("    CcSetFileSizes()\n"));
                        CcSetFileSizes(FileObject, (PCC_FILE_SIZES)&Fcb->Header.AllocationSize);
                        Fcb->NtReqFCBFlags |= UDF_NTREQ_FCB_MODIFIED;
                    }
                    // Attempt to Zero newly added fragment
                    // and ignore the return code
                    // This should be done to inform cache manager
                    // that given extent has no cached data
                    // (Otherwise, CM sometimes thinks that it has)
                    if (ZeroBlock) {
                        Fcb->NtReqFCBFlags |= UDF_NTREQ_FCB_MODIFIED;
                        ThPrint(("    UDFZeroDataEx(1)\n"));
                        UDFZeroData(Vcb,
                                    FileObject,
                                    OldVDL,
                                    Fcb->Header.FileSize.QuadPart - OldVDL,
                                    Wait);
#ifdef UDF_DBG
                        ZeroBlockDone = TRUE;
#endif //UDF_DBG
                    }
                }
            }

        }

        // Branch here for cached vs non-cached I/O

        if (!NonCachedIo) {

            // The caller wishes to perform cached I/O. Initiate caching if
            // this is the first cached I/O operation using this file object

            if (!FileObject->PrivateCacheMap) {

                // This is the first cached I/O operation. You must ensure
                // that the FCB Header contains valid sizes at this time

                CcInitializeCacheMap(FileObject,
                                     (PCC_FILE_SIZES)&Fcb->Header.AllocationSize,
                                     FALSE,
                                     &UdfData.CacheMgrCallBacks,
                                     Fcb);

                CcSetReadAheadGranularity(FileObject, READ_AHEAD_GRANULARITY);
            }

            if (ZeroBlock && !ZeroBlockDone) {
                ThPrint(("    UDFZeroDataEx(2)\n"));
                UDFZeroData(Vcb,
                            FileObject,
                            OldVDL,
                            StartingOffset + TruncatedLength - OldVDL,
                            Wait);
                if (StartingOffset & (PAGE_SIZE-1)) {
                }
            }

            // Write to the cache if this is not an Mdl read.

            if (!FlagOn( IrpContext->MinorFunction, IRP_MN_MDL)) {

                // Get hold of the user's buffer.

                SystemBuffer = UDFMapUserBuffer(Irp);

                Fcb->NtReqFCBFlags |= UDF_NTREQ_FCB_MODIFIED;

                if (!CcCopyWrite(FileObject,
                                 (PLARGE_INTEGER)&StartingOffset,
                                 TruncatedLength,
                                 Wait,
                                 SystemBuffer)) {

                    // The caller was not prepared to block and data is not immediately
                    // available in the system cache
                    // Mark Irp Pending ...
                    try_return(Status = STATUS_PENDING);
                }

                UDFUnlockCallersBuffer(IrpContext, Irp, SystemBuffer);
                // We have the data
                Status = STATUS_SUCCESS;
                NumberBytesWritten = TruncatedLength;

                try_return(Status);

                // Otherwise perform the MdlRead operation.

            } else {
                // Caller does want a MDL returned. Note that this mode
                // implies that the caller is prepared to block
                MmPrint(("    CcPrepareMdlWrite()\n"));
//                CcPrepareMdlWrite(FileObject, &ByteOffset, TruncatedLength, &(Irp->MdlAddress), &(Irp->IoStatus));
//                NumberBytesWritten = Irp->IoStatus.Information;
//                RC = Irp->IoStatus.Status;

                NumberBytesWritten = 0;
                Status = STATUS_INVALID_PARAMETER;

                try_return(Status);
            }
        } else {

            MmPrint(("    Write NonCachedIo\n"));

            // We needn't call CcZeroData here (like in Fat driver)
            // 'cause we've already done it above
            // (see call to UDFZeroDataEx() )
            if (!RecursiveWriteThrough &&
                !IsLazyWriteThread &&
                (OldVDL < StartingOffset)) {
#ifdef UDF_DBG
                    ASSERT(!ZeroBlockDone);
#endif //UDF_DBG
                    UDFZeroData(Vcb,
                                FileObject,
                                OldVDL,
                                StartingOffset - OldVDL,
                                Wait);
            }
            if (OldVDL < (StartingOffset + TruncatedLength)) {
                Fcb->Header.ValidDataLength.QuadPart = StartingOffset + TruncatedLength;
            }

            // Send the request to lower level drivers
            if (!Wait) {

                try_return(Status = STATUS_PENDING);
            }

            // Lock the callers buffer

            if (!NT_SUCCESS(Status = UDFLockUserBuffer(IrpContext, TruncatedLength, IoReadAccess))) {
                try_return(Status);
            }

            SystemBuffer = UDFMapUserBuffer(Irp);
            if (!SystemBuffer) {
                try_return(Status = STATUS_INVALID_USER_BUFFER);
            }
            Fcb->NtReqFCBFlags |= UDF_NTREQ_FCB_MODIFIED;

            // Acquire PagingIoResource exclusive to serialize with
            // UDFMarkAllocatedAsRecorded which may free and replace
            // ExtInfo->Mapping during NOT_RECORDED -> RECORDED conversion.
            // Without this, a concurrent UDFResizeExtent (holding PagingIoResource
            // exclusive for file extension) can use a stale Mapping pointer
            // that was freed by our UDFMarkAllocatedAsRecorded call.
            if (!PagingIoResourceAcquired) {
                UDFAcquirePagingIoExclusive(IrpContext, Fcb);
                PagingIoResourceAcquired = TRUE;
            }

            if (Fcb->FcbState & UDF_FCB_EMBEDDED_DATA) {

                //  In-ICB (embedded) data — write via extent walker
                //  (data lives inside the ICB sector, no disk extent to dispatch).

                Status = UDFWriteFile__(IrpContext, Vcb, Fcb->FileInfo, StartingOffset, TruncatedLength,
                               FALSE, (PCHAR)SystemBuffer, &NumberBytesWritten);
            } else {

                //
                //  Initialize the IoContext for the write (always synchronous).
                //

                IrpContext->IoContext = &LocalIoContext;
                ClearFlag(IrpContext->Flags, IRP_CONTEXT_FLAG_ALLOC_IO);

                RtlZeroMemory(&LocalIoContext, sizeof(UDF_IO_CONTEXT));

                KeInitializeEvent(&LocalIoContext.SyncEvent,
                                  NotificationEvent,
                                  FALSE);

                Status = UDFNonCachedIo(IrpContext, Fcb, StartingOffset, TruncatedLength);
                IrpContext->IoContext = NULL;
                NumberBytesWritten = (ULONG)Irp->IoStatus.Information;
            }

            UDFUnlockCallersBuffer(IrpContext, Irp, SystemBuffer);

            ASize = UDFGetFileAllocationSize(Vcb, Fcb->FileInfo);
            UDFSetFileSizeInDirNdx(Vcb, Fcb->FileInfo, &ASize);

            try_return(Status);
        }

try_exit:   NOTHING;

    } _SEH2_FINALLY {

        if (Irp != NULL) {
            Irp->IoStatus.Information = NumberBytesWritten;
            Irp->IoStatus.Status = Status;
        }

        if (NT_SUCCESS(Status) && !AbnormalTermination()) {

            // For synchronous I/O, the FSD must maintain the current byte offset
            // Do not do this however, if I/O is marked as paging-io

            if (SynchronousIo && !PagingIo && NT_SUCCESS(Status)) {
                FileObject->CurrentByteOffset.QuadPart = StartingOffset + NumberBytesWritten;
            }

            // If the write completed successfully and this was not a paging-io
            // operation, set a flag in the CCB that indicates that a write was
            // performed and that the file time should be updated at cleanup

            if (NT_SUCCESS(Status) && !PagingIo) {

                // If the file size was changed, set a flag in the FCB indicating that
                // this occurred.
                SetFlag(FileObject->Flags, FO_FILE_MODIFIED);

                if (FileSizesChanged) {

                    SetFlag(FileObject->Flags, FO_FILE_SIZE_CHANGED);
                }

                // Update ValidDataLength
                if (!IsLazyWriteThread) {

                    if (Fcb->Header.ValidDataLength.QuadPart < (StartingOffset + NumberBytesWritten)) {

                        Fcb->Header.ValidDataLength.QuadPart =
                            min(Fcb->Header.FileSize.QuadPart,
                                StartingOffset + NumberBytesWritten);

                        if (NonCachedIo && CcIsFileCached(FileObject)) {
                            CcSetFileSizes(FileObject, (PCC_FILE_SIZES)&Fcb->Header.AllocationSize);
                        }
                    }
                }
            }
        }

        // Release any resources acquired here ...

        if (PagingIoResourceAcquired) {
            UDFReleasePagingIo(IrpContext, Fcb);
        }

        if (MainResourceAcquired) {
            UDFReleaseFcb(IrpContext, Fcb);
        }

        if (VcbAcquired) {
            UDFReleaseVcb(IrpContext, Vcb);
        }

    } _SEH2_END; // end of "__finally" processing

    // Post IRP if required

    if (Status == STATUS_PENDING) {

        Status = UDFFsdPostRequest(IrpContext, Irp);

    } else {

        UDFCompleteRequest(IrpContext, Irp, Status);
    }

    UDFPrint(("\n"));
    return(Status);
} // end UDFCommonWrite()

/*************************************************************************
*
* Function: UDFDeferredWriteCallBack()
*
* Description:
*   Invoked by the cache manager in the context of a worker thread.
*   Typically, you can simply post the request at this point (just
*   as you would have if the original request could not block) to
*   perform the write in the context of a system worker thread.
*
* Expected Interrupt Level (for execution) :
*
*  IRQL_PASSIVE_LEVEL
*
* Return Value: None
*
*************************************************************************/
VOID
NTAPI
UDFDeferredWriteCallBack(
    IN PVOID Context1,          // Should be IrpContext
    IN PVOID Context2           // Should be Irp
    )
{
    UDFPrint(("UDFDeferredWriteCallBack\n"));
    // We should typically simply post the request to our internal
    // queue of posted requests (just as we would if the original write
    // could not be completed because the caller could not block).
    // Once we post the request, return from this routine. The write
    // will then be retried in the context of a system worker thread
    UDFAddToWorkque((PIRP_CONTEXT)Context1, (PIRP)Context2);

} // end UDFDeferredWriteCallBack()

/*************************************************************************
*
*************************************************************************/

#define USE_CcCopyWrite_TO_ZERO

VOID
UDFPurgeCacheEx_(
    PFCB                Fcb,
    LONGLONG            Offset,
    LONGLONG            Length,
//#ifndef ALLOW_SPARSE
    BOOLEAN             CanWait,
//#endif //ALLOW_SPARSE
    PVCB                Vcb,
    PFILE_OBJECT        FileObject
    )
{
    ULONG Off_l = 0;
#ifdef USE_CcCopyWrite_TO_ZERO
    ULONG PgLen = 0;
#endif //USE_CcCopyWrite_TO_ZERO

    // We'll just purge cache section here,
    // without call to CcZeroData()
    // 'cause udf_info.cpp will care about it

#define PURGE_BLOCK_SZ 0x10000000

    // NOTE: if FS engine doesn't suport
    // sparse/unrecorded areas, CcZeroData must be called
    // In this case we'll see some recursive WRITE requests

    _SEH2_TRY {
        MmPrint(("    UDFPurgeCacheEx_():  Offs: %I64x, ", Offset));
        MmPrint((" Len: %lx\n", Length));
        SECTION_OBJECT_POINTERS* SectionObject = &Fcb->FcbNonpaged->SegmentObject;
        if (Length) {
            LONGLONG Offset0, OffsetX, VDL;

            Offset0 = Offset;
            if ((Off_l = ((ULONG)Offset0 & (PAGE_SIZE-1)))) {
                //                 Offset, Offset0
                //                 v
                // ...|dddddddddddd00000|....
                //    |<- Off_l ->|
#ifndef USE_CcCopyWrite_TO_ZERO
                *((PULONG)&Offset0) &= ~(PAGE_SIZE-1);
                MmPrint(("    CcFlushCache(s) Offs %I64x, Len %x\n", Offset0, Off_l));
                CcFlushCache( SectionObject, (PLARGE_INTEGER)&Offset0, Off_l, NULL );
#else //USE_CcCopyWrite_TO_ZERO
                // ...|ddddd000000000000|....
                //          |<- PgLen ->|
                PgLen = PAGE_SIZE - Off_l; /*(*((PULONG)&Offset) & (PAGE_SIZE-1))*/
                //
                if (PgLen > Length)
                    PgLen = (ULONG)Length;

                MmPrint(("    ZeroCache (CcWrite) Offs %I64x, Len %x\n", Offset, PgLen));
#ifdef DBG
                if (FileObject && Vcb) {

                    ASSERT(CanWait);
#endif //DBG
                    if (PgLen) {
                        if (SectionObject->SharedCacheMap) {
                            CcCopyWrite(FileObject, (PLARGE_INTEGER)&Offset, PgLen, TRUE || CanWait, Vcb->ZBuffer);
                        }
                        Offset += PgLen;
                        Length -= PgLen;
                    }
#ifdef DBG
                } else {
                    MmPrint(("    Can't use CcWrite to zero cache\n"));
                }
#endif //DBG
#endif //USE_CcCopyWrite_TO_ZERO
            }
            VDL = Fcb->Header.ValidDataLength.QuadPart;
            OffsetX = Offset+Length;
            if ((Off_l = ((ULONG)OffsetX & (PAGE_SIZE-1)))) {

                if (OffsetX < VDL) {
#ifndef USE_CcCopyWrite_TO_ZERO
                    Off_l = ( (ULONG)(VDL-OffsetX) > PAGE_SIZE ) ?
                        (PAGE_SIZE - Off_l) :
                        ((ULONG)(VDL-OffsetX));
                    *((PULONG)&OffsetX) &= ~(PAGE_SIZE-1);
                    MmPrint(("    CcFlushCache(e) Offs %I64x, Len %x\n", OffsetX, Off_l));
                    CcFlushCache( SectionObject, (PLARGE_INTEGER)&OffsetX, Off_l, NULL );
#else //USE_CcCopyWrite_TO_ZERO
                    if (VDL - OffsetX > PAGE_SIZE) {
                        PgLen = (ULONG)OffsetX & ~(PAGE_SIZE-1);
                    } else {
                        PgLen = (ULONG)(VDL - OffsetX) & ~(PAGE_SIZE-1);
                    }
                    // ...|000000000000ddddd|....
                    //    |<- PgLen ->|
                    MmPrint(("    ZeroCache (CcWrite - 2) Offs %I64x, Len %x\n", OffsetX, PgLen));
#ifdef DBG
                    if (FileObject && Vcb) {
                        ASSERT(CanWait);
#endif //DBG
                        if (SectionObject->SharedCacheMap) {
                            CcCopyWrite(FileObject, (PLARGE_INTEGER)&OffsetX, PgLen, TRUE || CanWait, Vcb->ZBuffer);
                        }
                        Length -= PgLen;
#ifdef DBG
                    } else {
                        MmPrint(("    Can't use CcWrite to zero cache (2)\n"));
                    }
#endif //DBG
#endif //USE_CcCopyWrite_TO_ZERO
                }
            }
#ifndef USE_CcCopyWrite_TO_ZERO
            do
#else //USE_CcCopyWrite_TO_ZERO
            while(Length)
#endif //USE_CcCopyWrite_TO_ZERO
            {
                MmPrint(("    CcPurgeCacheSection()\n"));
                if (PURGE_BLOCK_SZ > Length) {
                    CcPurgeCacheSection(SectionObject, (PLARGE_INTEGER)&Offset,
                                                (ULONG)Length, FALSE);
    /*
                    NtReqFcb->CommonFCBHeader.ValidDataLength.QuadPart += Length;
                    ASSERT(NtReqFcb->CommonFCBHeader.ValidDataLength.QuadPart <=
                           NtReqFcb->CommonFCBHeader.FileSize.QuadPart);
                    MmPrint(("    CcFlushCache()\n"));
                    CcFlushCache( SectionObject, (PLARGE_INTEGER)&Offset, (ULONG)Length, NULL );
    */
#ifndef ALLOW_SPARSE
        //            UDFZeroFile__(
#endif //ALLOW_SPARSE
                    break;
                } else {
                    CcPurgeCacheSection(SectionObject, (PLARGE_INTEGER)&Offset,
                                                PURGE_BLOCK_SZ, FALSE);
    /*
                    NtReqFcb->CommonFCBHeader.ValidDataLength.QuadPart += PURGE_BLOCK_SZ;
                    ASSERT(NtReqFcb->CommonFCBHeader.ValidDataLength.QuadPart <=
                           NtReqFcb->CommonFCBHeader.FileSize.QuadPart);
                    MmPrint(("    CcFlushCache()\n"));
                    CcFlushCache( SectionObject, (PLARGE_INTEGER)&Offset, (ULONG)Length, NULL );
    */
#ifndef ALLOW_SPARSE
        //            UDFZeroFile__(
#endif //ALLOW_SPARSE
                    Length -= PURGE_BLOCK_SZ;
                    Offset += PURGE_BLOCK_SZ;
                }
            }
#ifndef USE_CcCopyWrite_TO_ZERO
            while(Length);
#endif //USE_CcCopyWrite_TO_ZERO
            if (VDL < Offset)
                Fcb->Header.ValidDataLength.QuadPart = Offset;
        }
    } _SEH2_EXCEPT(EXCEPTION_EXECUTE_HANDLER) {
        BrutePoint();
    } _SEH2_END;
} // end UDFPurgeCacheEx_()

BOOLEAN
UDFZeroData (
    IN PVCB Vcb,
    IN PFILE_OBJECT FileObject,
    IN ULONG StartingZero,
    IN ULONG ByteCount,
    BOOLEAN CanWait
    )

/*++

    **** Temporary function - Remove when CcZeroData is capable of handling
    non sector aligned requests.

--*/
{
    LARGE_INTEGER ZeroStart = {0,0};
    LARGE_INTEGER BeyondZeroEnd = {0,0};

    BOOLEAN Finished = FALSE;

    PAGED_CODE();

    ULONG LBS = Vcb->SectorSize;

    ZeroStart.LowPart = (StartingZero + (LBS - 1)) & ~(LBS - 1);

    //
    //  Detect overflow if we were asked to zero in the last sector of the file,
    //  which must be "zeroed" already (or we're in trouble).
    //
    
    if (StartingZero != 0 && ZeroStart.LowPart == 0) {
        
        return TRUE;
    }

    //
    //  Note that BeyondZeroEnd can take the value 4gb.
    //
    
    BeyondZeroEnd.QuadPart = ((ULONGLONG) StartingZero + ByteCount + (LBS - 1))
                             & (~((LONGLONG) LBS - 1));

    //
    //  If we were called to just zero part of a sector we are in trouble.
    //
    
    if ( ZeroStart.QuadPart == BeyondZeroEnd.QuadPart ) {

        return TRUE;
    }

    Finished = CcZeroData( FileObject,
                           &ZeroStart,
                           &BeyondZeroEnd,
                           CanWait );

    return Finished;
}
